#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/moneyK?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: mysql
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create